
from django.contrib.auth.forms import forms


class year_country(forms.Form):
    y=[('All','All'),(2016, 2016), (2014, 2014), (2012, 2012), (2010, 2010), (2008, 2008),
       (2006, 2006), (2004, 2004), (2002, 2002), (2000, 2000), (1998, 1998), (1996, 1996),
       (1994, 1994), (1992, 1992), (1988, 1988), (1984, 1984), (1980, 1980), (1976, 1976), (1972, 1972),
       (1968, 1968), (1964, 1964), (1960, 1960), (1956, 1956), (1952, 1952), (1948, 198),
       (1936, 1936), (1932, 1932), (1928, 1928), (1924, 1924), (1920, 1920), (1912, 1912), (1908, 1908), (1906, 1906), (1904, 1904), (1900, 1900), (1896, 1896)]
    c=[('All','All'),('Afghanistan', 'Afghanistan'), ('Albania', 'Albania'), ('Algeria', 'Algeria'), ('American Samoa', 'American Samoa'), ('Andorra', 'Andorra'), ('Angola', 'Angola'),
       ('Antigua', 'Antigua'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), ('Aruba', 'Aruba'), ('Australia', 'Australia'), ('Austria', 'Austria'),
       ('Azerbaijan', 'Azerbaijan'), ('Bahamas', 'Bahamas'), ('Bahrain', 'Bahrain'), ('Bangladesh', 'Bangladesh'), ('Barbados', 'Barbados'), ('Belarus', 'Belarus'),
       ('Belgium', 'Belgium'), ('Belize', 'Belize'), ('Benin', 'Benin'), ('Bermuda', 'Bermuda'), ('Bhutan', 'Bhutan'), ('Boliva', 'Boliva'), ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'),
       ('Botswana', 'Botswana'), ('Brazil', 'Brazil'), ('Brunei', 'Brunei'), ('Bulgaria', 'Bulgaria'), ('Burkina Faso', 'Burkina Faso'), ('Burundi', 'Burundi'),
       ('Cambodia', 'Cambodia'), ('Cameroon', 'Cameroon'), ('Canada', 'Canada'), ('Cape Verde', 'Cape Verde'), ('Cayman Islands', 'Cayman Islands'), ('Central African Republic', 'Central African Republic'),
       ('Chad', 'Chad'), ('Chile', 'Chile'), ('China', 'China'), ('Colombia', 'Colombia'), ('Comoros', 'Comoros'), ('Cook Islands', 'Cook Islands'),
       ('Costa Rica', 'Costa Rica'), ('Croatia', 'Croatia'), ('Cuba', 'Cuba'), ('Curacao', 'Curacao'), ('Cyprus', 'Cyprus'), ('Czech Republic', 'Czech Republic'),
       ('Democratic Republic of the Congo', 'Democratic Republic of the Congo'), ('Denmark', 'Denmark'), ('Djibouti', 'Djibouti'), ('Dominica', 'Dominica'),
       ('Dominican Republic', 'Dominican Republic'), ('Ecuador', 'Ecuador'), ('Egypt', 'Egypt'), ('El Salvador', 'El Salvador'), ('Equatorial Guinea', 'Equatorial Guinea'), ('Eritrea', 'Eritrea'), ('Estonia', 'Estonia'), ('Ethiopia', 'Ethiopia'), ('Fiji', 'Fiji'), ('Finland', 'Finland'), ('France', 'France'),
       ('Gabon', 'Gabon'), ('Gambia', 'Gambia'), ('Georgia', 'Georgia'), ('Germany', 'Germany'), ('Ghana', 'Ghana'), ('Greece', 'Greece'), ('Grenada', 'Grenada'), ('Guam', 'Guam'), ('Guatemala', 'Guatemala'), ('Guinea', 'Guinea'), ('Guinea-Bissau', 'Guinea-Bissau'), ('Guyana', 'Guyana'), ('Haiti', 'Haiti'), ('Honduras', 'Honduras'), ('Hungary', 'Hungary'), ('Iceland', 'Iceland'), ('India', 'India'), ('Individual Olympic Athletes', 'Individual Olympic Athletes'), ('Indonesia', 'Indonesia'),
       ('Iran', 'Iran'), ('Iraq', 'Iraq'), ('Ireland', 'Ireland'), ('Israel','Israel'), ('Italy', 'Italy'), ('Ivory Coast', 'Ivory Coast'), ('Jamaica', 'Jamaica'), ('Japan', 'Japan'), ('Jordan', 'Jordan'), ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Kiribati', 'Kiribati'), ('Kosovo', 'Kosovo'), ('Kuwait', 'Kuwait'),
       ('Kyrgyzstan', 'Kyrgyzstan'), ('Laos', 'Laos'), ('Latvia', 'Latvia'), ('Lebanon', 'Lebanon'), ('Lesotho', 'Lesotho'), ('Liberia', 'Liberia'), ('Libya', 'Libya'), ('Liechtenstein', 'Liechtenstein'), ('Lithuania', 'Lithuania'), ('Luxembourg', 'Luxembourg'), ('Macedonia', 'Macedonia'), ('Madagascar', 'Madagascar'), ('Malawi', 'Malawi'), ('Malaysia', 'Malaysia'), ('Maldives', 'Maldives'), ('Mali', 'Mali'),
       ('Malta','Malta'), ('Marshall Islands', 'Marshall Islands'), ('Mauritania', 'Mauritania'), ('Mauritius', 'Mauritius'), ('Mexico', 'Mexico'), ('Micronesia', 'Micronesia'), ('Moldova', 'Moldova'), ('Monaco', 'Monaco'), ('Mongolia', 'Mongolia'), ('Montenegro', 'Montenegro'),
       ('Morocco', 'Morocco'), ('Mozambique', 'Mozambique'), ('Myanmar', 'Myanmar'), ('Namibia', 'Namibia'), ('Nauru', 'Nauru'), ('Nepal', 'Nepal'), ('Netherlands', 'Netherlands'), ('New Zealand', 'New Zealand'), ('Nicaragua', 'Nicaragua'),('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('North Korea', 'North Korea'), ('Norway', 'Norway'), ('Oman', 'Oman'), ('Pakistan', 'Pakistan'), ('Palau', 'Palau'),
       ('Palestine', 'Palestine'), ('Panama', 'Panama'), ('Papua New Guinea', 'Papua New Guinea'), ('Paraguay', 'Paraguay'), ('Peru', 'Peru'), ('Philippines', 'Philippines'), ('Poland', 'Poland'), ('Portugal', 'Portugal'), ('Puerto Rico', 'Puerto Rico'), ('Qatar', 'Qatar'), ('Republic of Congo', 'Republic of Congo'), ('Romania', 'Romania'),
       ('Russia', 'Russia'), ('Rwanda', 'Rwanda'), ('Saint Kitts', 'Saint Kitts'), ('Saint Lucia', 'Saint Lucia'), ('Saint Vincent', 'Saint Vincent'), ('Samoa', 'Samoa'), ('San Marino', 'San Marino'), ('Sao Tome and Principe', 'Sao Tome and Principe'), ('Saudi Arabia', 'Saudi Arabia'), ('Senegal', 'Senegal'), ('Serbia', 'Serbia'), ('Seychelles', 'Seychelles'), ('Sierra Leone', 'Sierra Leone'), ('Slovakia', 'Slovakia'), ('Slovenia', 'Slovenia'),
       ('Solomon Islands', 'Solomon Islands'), ('Somalia', 'Somalia'), ('South Africa', 'South Africa'), ('South Korea', 'South Korea'), ('South Sudan', 'South Sudan'), ('Spain', 'Spain'), ('Sri Lanka', 'Sri Lanka'), ('Sudan', 'Sudan'), ('Suriname', 'Suriname'), ('Swaziland', 'Swaziland'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Syria', 'Syria'), ('Taiwan', 'Taiwan'), ('Tajikistan', 'Tajikistan'), ('Tanzania', 'Tanzania'), ('Thailand', 'Thailand'), ('Timor-Leste', 'Timor-Leste'),
       ('Togo', 'Togo'), ('Tonga', 'Tonga'), ('Trinidad', 'Trinidad'), ('Tunisia', 'Tunisia'), ('Turkey', 'Turkey'), ('Turkmenistan', 'Turkmenistan'), ('UK', 'UK'), ('USA', 'USA'), ('Uganda', 'Uganda'), ('Ukraine', 'Ukraine'), ('United Arab Emirates', 'United Arab Emirates'), ('Uruguay', 'Uruguay'), ('Uzbekistan', 'Uzbekistan'), ('Vanuatu', 'Vanuatu'), ('Venezuela', 'Venezuela'), ('Vietnam', 'Vietnam'), ('Virgin Islands, British', 'Virgin Islands, British'), ('Virgin Islands, US', 'Virgin Islands, US'), ('Yemen', 'Yemen'), ('Zambia', 'Zambia'), ('Zimbabwe','Zimbabwe')]

    Year=forms.ChoiceField(choices=y,initial='All')
    Country=forms.ChoiceField(choices=c,initial='All')

class Overanalysis(forms.Form):
   sp=[('All','All'),('Basketball', 'Basketball'),('Judo', 'Judo'),('Football', 'Football'),
              ('Tug-Of-War', 'Tug-Of-War'),
                     ('Speed Skating', 'Speed Skating'),
                      ('Cross Country Skiing', 'Cross Country Skiing'),
                   ('Athletics', 'Athletics'),
               ('Ice Hockey', 'Ice Hockey'),
 ('Swimming', 'Swimming'),
 ('Badminton', 'Badminton'),
 ('Sailing', 'Sailing'),
 ('Biathlon', 'Biathlon'),
 ('Gymnastics', 'Gymnastics'),
 ('Art Competitions', 'Art Competitions'),
 ('Alpine Skiing', 'Alpine Skiing'),
 ('Handball', 'Handball'),
 ('Weightlifting', 'Weightlifting'),
 ('Wrestling', 'Wrestling'),
 ('Luge', 'Luge'),
 ('Water Polo', 'Water Polo'),
 ('Hockey', 'Hockey'),
 ('Rowing', 'Rowing'),
 ('Bobsleigh', 'Bobsleigh'),
 ('Fencing', 'Fencing'),
 ('Equestrianism', 'Equestrianism'),
 ('Shooting', 'Shooting'),
 ('Boxing', 'Boxing'),
 ('Taekwondo', 'Taekwondo'),
 ('Cycling', 'Cycling'),
 ('Diving', 'Diving'),
 ('Canoeing', 'Canoeing'),
 ('Tennis', 'Tennis'),
 ('Modern Pentathlon', 'Modern Pentathlon'),
 ('Figure Skating', 'Figure Skating'),
 ('Golf', 'Golf'),
 ('Softball', 'Softball'),
 ('Archery', 'Archery'),
 ('Volleyball', 'Volleyball'),
 ('Synchronized Swimming', 'Synchronized Swimming'),
 ('Table Tennis', 'Table Tennis'),
 ('Nordic Combined', 'Nordic Combined'),
 ('Baseball', 'Baseball'),
 ('Rhythmic Gymnastics', 'Rhythmic Gymnastics'),
 ('Freestyle Skiing', 'Freestyle Skiing'),
 ('Rugby Sevens', 'Rugby Sevens'),
 ('Trampolining', 'Trampolining'),
 ('Beach Volleyball', 'Beach Volleyball'),
 ('Triathlon', 'Triathlon'),
 ('Ski Jumping', 'Ski Jumping'),
 ('Curling', 'Curling'),
 ('Snowboarding', 'Snowboarding'),
 ('Rugby', 'Rugby'),
 ('Short Track Speed Skating', 'Short Track Speed Skating'),
 ('Skeleton', 'Skeleton'),
 ('Lacrosse', 'Lacrosse'),
 ('Polo', 'Polo'),
 ('Cricket', 'Cricket'),
 ('Racquets', 'Racquets'),
 ('Motorboating', 'Motorboating'),
 ('Military Ski Patrol', 'Military Ski Patrol'),
 ('Croquet', 'Croquet'),
 ('Jeu De Paume', 'Jeu De Paume'),
 ('Roque', 'Roque'),
 ('Alpinism', 'Alpinism'),
 ('Basque Pelota', 'Basque Pelota'),
 ('Aeronautics', 'Aeronautics')]
   search_sport=forms.ChoiceField(choices=sp,initial='All')


class year_form(forms.Form):
    cp = [('All', 'All'), ('Afghanistan', 'Afghanistan'), ('Albania', 'Albania'), ('Algeria', 'Algeria'),
         ('American Samoa', 'American Samoa'), ('Andorra', 'Andorra'), ('Angola', 'Angola'),
         ('Antigua', 'Antigua'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), ('Aruba', 'Aruba'),
         ('Australia', 'Australia'), ('Austria', 'Austria'),
         ('Azerbaijan', 'Azerbaijan'), ('Bahamas', 'Bahamas'), ('Bahrain', 'Bahrain'), ('Bangladesh', 'Bangladesh'),
         ('Barbados', 'Barbados'), ('Belarus', 'Belarus'),
         ('Belgium', 'Belgium'), ('Belize', 'Belize'), ('Benin', 'Benin'), ('Bermuda', 'Bermuda'), ('Bhutan', 'Bhutan'),
         ('Boliva', 'Boliva'), ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'),
         ('Botswana', 'Botswana'), ('Brazil', 'Brazil'), ('Brunei', 'Brunei'), ('Bulgaria', 'Bulgaria'),
         ('Burkina Faso', 'Burkina Faso'), ('Burundi', 'Burundi'),
         ('Cambodia', 'Cambodia'), ('Cameroon', 'Cameroon'), ('Canada', 'Canada'), ('Cape Verde', 'Cape Verde'),
         ('Cayman Islands', 'Cayman Islands'), ('Central African Republic', 'Central African Republic'),
         ('Chad', 'Chad'), ('Chile', 'Chile'), ('China', 'China'), ('Colombia', 'Colombia'), ('Comoros', 'Comoros'),
         ('Cook Islands', 'Cook Islands'),
         ('Costa Rica', 'Costa Rica'), ('Croatia', 'Croatia'), ('Cuba', 'Cuba'), ('Curacao', 'Curacao'),
         ('Cyprus', 'Cyprus'), ('Czech Republic', 'Czech Republic'),
         ('Democratic Republic of the Congo', 'Democratic Republic of the Congo'), ('Denmark', 'Denmark'),
         ('Djibouti', 'Djibouti'), ('Dominica', 'Dominica'),
         ('Dominican Republic', 'Dominican Republic'), ('Ecuador', 'Ecuador'), ('Egypt', 'Egypt'),
         ('El Salvador', 'El Salvador'), ('Equatorial Guinea', 'Equatorial Guinea'), ('Eritrea', 'Eritrea'),
         ('Estonia', 'Estonia'), ('Ethiopia', 'Ethiopia'), ('Fiji', 'Fiji'), ('Finland', 'Finland'),
         ('France', 'France'),
         ('Gabon', 'Gabon'), ('Gambia', 'Gambia'), ('Georgia', 'Georgia'), ('Germany', 'Germany'), ('Ghana', 'Ghana'),
         ('Greece', 'Greece'), ('Grenada', 'Grenada'), ('Guam', 'Guam'), ('Guatemala', 'Guatemala'),
         ('Guinea', 'Guinea'), ('Guinea-Bissau', 'Guinea-Bissau'), ('Guyana', 'Guyana'), ('Haiti', 'Haiti'),
         ('Honduras', 'Honduras'), ('Hungary', 'Hungary'), ('Iceland', 'Iceland'), ('India', 'India'),
         ('Individual Olympic Athletes', 'Individual Olympic Athletes'), ('Indonesia', 'Indonesia'),
         ('Iran', 'Iran'), ('Iraq', 'Iraq'), ('Ireland', 'Ireland'), ('Israel', 'Israel'), ('Italy', 'Italy'),
         ('Ivory Coast', 'Ivory Coast'), ('Jamaica', 'Jamaica'), ('Japan', 'Japan'), ('Jordan', 'Jordan'),
         ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Kiribati', 'Kiribati'), ('Kosovo', 'Kosovo'),
         ('Kuwait', 'Kuwait'),
         ('Kyrgyzstan', 'Kyrgyzstan'), ('Laos', 'Laos'), ('Latvia', 'Latvia'), ('Lebanon', 'Lebanon'),
         ('Lesotho', 'Lesotho'), ('Liberia', 'Liberia'), ('Libya', 'Libya'), ('Liechtenstein', 'Liechtenstein'),
         ('Lithuania', 'Lithuania'), ('Luxembourg', 'Luxembourg'), ('Macedonia', 'Macedonia'),
         ('Madagascar', 'Madagascar'), ('Malawi', 'Malawi'), ('Malaysia', 'Malaysia'), ('Maldives', 'Maldives'),
         ('Mali', 'Mali'),
         ('Malta', 'Malta'), ('Marshall Islands', 'Marshall Islands'), ('Mauritania', 'Mauritania'),
         ('Mauritius', 'Mauritius'), ('Mexico', 'Mexico'), ('Micronesia', 'Micronesia'), ('Moldova', 'Moldova'),
         ('Monaco', 'Monaco'), ('Mongolia', 'Mongolia'), ('Montenegro', 'Montenegro'),
         ('Morocco', 'Morocco'), ('Mozambique', 'Mozambique'), ('Myanmar', 'Myanmar'), ('Namibia', 'Namibia'),
         ('Nauru', 'Nauru'), ('Nepal', 'Nepal'), ('Netherlands', 'Netherlands'), ('New Zealand', 'New Zealand'),
         ('Nicaragua', 'Nicaragua'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('North Korea', 'North Korea'),
         ('Norway', 'Norway'), ('Oman', 'Oman'), ('Pakistan', 'Pakistan'), ('Palau', 'Palau'),
         ('Palestine', 'Palestine'), ('Panama', 'Panama'), ('Papua New Guinea', 'Papua New Guinea'),
         ('Paraguay', 'Paraguay'), ('Peru', 'Peru'), ('Philippines', 'Philippines'), ('Poland', 'Poland'),
         ('Portugal', 'Portugal'), ('Puerto Rico', 'Puerto Rico'), ('Qatar', 'Qatar'),
         ('Republic of Congo', 'Republic of Congo'), ('Romania', 'Romania'),
         ('Russia', 'Russia'), ('Rwanda', 'Rwanda'), ('Saint Kitts', 'Saint Kitts'), ('Saint Lucia', 'Saint Lucia'),
         ('Saint Vincent', 'Saint Vincent'), ('Samoa', 'Samoa'), ('San Marino', 'San Marino'),
         ('Sao Tome and Principe', 'Sao Tome and Principe'), ('Saudi Arabia', 'Saudi Arabia'), ('Senegal', 'Senegal'),
         ('Serbia', 'Serbia'), ('Seychelles', 'Seychelles'), ('Sierra Leone', 'Sierra Leone'), ('Slovakia', 'Slovakia'),
         ('Slovenia', 'Slovenia'),
         ('Solomon Islands', 'Solomon Islands'), ('Somalia', 'Somalia'), ('South Africa', 'South Africa'),
         ('South Korea', 'South Korea'), ('South Sudan', 'South Sudan'), ('Spain', 'Spain'), ('Sri Lanka', 'Sri Lanka'),
         ('Sudan', 'Sudan'), ('Suriname', 'Suriname'), ('Swaziland', 'Swaziland'), ('Sweden', 'Sweden'),
         ('Switzerland', 'Switzerland'), ('Syria', 'Syria'), ('Taiwan', 'Taiwan'), ('Tajikistan', 'Tajikistan'),
         ('Tanzania', 'Tanzania'), ('Thailand', 'Thailand'), ('Timor-Leste', 'Timor-Leste'),
         ('Togo', 'Togo'), ('Tonga', 'Tonga'), ('Trinidad', 'Trinidad'), ('Tunisia', 'Tunisia'), ('Turkey', 'Turkey'),
         ('Turkmenistan', 'Turkmenistan'), ('UK', 'UK'), ('USA', 'USA'), ('Uganda', 'Uganda'), ('Ukraine', 'Ukraine'),
         ('United Arab Emirates', 'United Arab Emirates'), ('Uruguay', 'Uruguay'), ('Uzbekistan', 'Uzbekistan'),
         ('Vanuatu', 'Vanuatu'), ('Venezuela', 'Venezuela'), ('Vietnam', 'Vietnam'),
         ('Virgin Islands, British', 'Virgin Islands, British'), ('Virgin Islands, US', 'Virgin Islands, US'),
         ('Yemen', 'Yemen'), ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe')]

    search_country=forms.ChoiceField(choices=cp,initial='USA')